---
name: build-platforms
run-name: ${{ github.actor }} is building all platforms
on: [push]
jobs:
  build-mingw-gcc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: gcc -o build.exe build_example.c -Wall -Wextra -pedantic -Werror
      - run: .\build.exe rebuild
  build-ubuntu-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: gcc -o build build_example.c -Wall -Wextra -pedantic -Werror -fsanitize=address
      - run: ./build rebuild
  build-ubuntu-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: clang -o build build_example.c -Wall -Wextra -pedantic -Werror -fsanitize=address
      - run: ./build rebuild
